apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: timber
  namespace: user0
spec:
  rules:
  - host: timber2.lvh.me
    http:
      paths:
      - backend:
          serviceName: timber-frontend
          servicePort: 8080
